#ifndef _LPC2106REG_H_
#define _LPC2106REG_H_

#define LPC_REGISTER volatile unsigned int

/* GPIO REGISTERS*/
typedef struct{
	LPC_REGISTER PIN;
	LPC_REGISTER SET;
	LPC_REGISTER DIR;
	LPC_REGISTER CLR;
} GPIO_STRUCT;

#define GPIO_BASE 0xE0028000
#define GPIO ((GPIO_STRUCT*)(GPIO_BASE))

/* PINSEL define a function of pin */
typedef struct{
	LPC_REGISTER PINSEL0;
	LPC_REGISTER PINSEL1;
} GPIO_PIN_STRUCT;

#define GPIO_PINSEL_BASE 0xE002C000
#define GPIO_PINSEL ((GPIO_PIN_STRUCT*)(GPIO_PINSEL_BASE))

/* Timer 0 REGISTERS*/

#define LPCFREQ 14745600
#define Fosc 14745600

typedef struct{
	LPC_REGISTER IR;
	LPC_REGISTER TCR;
	LPC_REGISTER TC;
	LPC_REGISTER PR;
	LPC_REGISTER PC;
} TIMER0_STRUCT;

#define TIMER0_BASE 0xE0004000
#define TIMER0 ((TIMER0_STRUCT*)(TIMER0_BASE))

/* RTC REGISTERS*/
typedef struct{
	LPC_REGISTER PREINT;
	LPC_REGISTER PREFRAC;
}RTC_CLK_STRUCT;

#define RTC_CLOCK_BASE 0xE0024080
#define RTC_CLOCK ((RTC_CLK_STRUCT*)(RTC_CLOCK_BASE))

typedef struct{
	LPC_REGISTER ILR;
	LPC_REGISTER CTC;
	LPC_REGISTER CCR;
	LPC_REGISTER CIIR;
	LPC_REGISTER AMR;
	LPC_REGISTER CTIME0;
	LPC_REGISTER CTIME1;
	LPC_REGISTER CTIME2;
	LPC_REGISTER SEC;
	LPC_REGISTER MIN;
	LPC_REGISTER HOUR;
	LPC_REGISTER DOM;
	LPC_REGISTER DOW;
	LPC_REGISTER DOY;
	LPC_REGISTER MONTH;
	LPC_REGISTER YEAR;
} RTC_STRUCT;

#define RTC_BASE 0xE0024000
#define RTC ((RTC_STRUCT*)(RTC_BASE))


/* PLL REGISTERS*/

typedef struct{
	LPC_REGISTER CON;
	LPC_REGISTER CFG;
	LPC_REGISTER STAT;
	LPC_REGISTER FEED;
} PLL_STRUCT;

#define PLL_BASE 0xE01FC080
#define PLL ((PLL_STRUCT*)(PLL_BASE))

typedef struct{
	LPC_REGISTER VPB_DIV;
} VPBDIV_STRUCT;

#define VPBDIV_BASE 0xE01FC080
#define VPBDIV ((VPBDIV_STRUCT*)(VPBDIV_BASE))


/* MASCARAS PARA BITS DA DATA DO RTC */
#define MASK_SEC 0x003F
#define MASK_MINUTE 0x3F00
#define MASK_HOUR 0x1F0000

#define MASK_DAY 0xF
#define MASK_MONTH 0xF00
#define MASK_YEAR 0xFFF0000

#define MASK_DAY_OF_YEAR 0xFFF
#define MASK_DAY_OF_WEEK 0x7000000

/* OFFSET DOS BITS DO RTC */
#define OFFSET_SEC 0x0
#define OFFSET_MINUTE 0x8
#define OFFSET_HOUR 0x10

#define OFFSET_DAY 0x0
#define OFFSET_MONTH 0x8
#define OFFSET_YEAR 0x10

#define OFFSET_DAY_OF_YEAR 0x0
#define OFFSET_DAY_OF_WEEK 0x18

/* *********** I2C ********** */
typedef struct{
	LPC_REGISTER CONSET;
	LPC_REGISTER STAT;
	LPC_REGISTER DAT;
	LPC_REGISTER ADR;
	LPC_REGISTER SCLH;
	LPC_REGISTER SCLL;
	LPC_REGISTER CONCLR;
} I2C_STRUCT;

#define I2C_BASE 0xE001C000
#define I2C ((I2C_STRUCT*)(I2C_BASE))
#define LPC_PWR 0xE01FC0C4


#endif
